name: example_timeline_tile
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  google_fonts: ^6.2.1
  timeline_tile: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
